### ISSUE TITLE
Suggestion: Add a local.py.example file

### ISSUE THREAD

**Issue by donbalon4** [animorphcoop/journey-coop#12]
Hi, I would like to suggest adding a local settings file example, something like journey/local.py.example in order to speed up local set up of dev env.

**Comment by nektdev** [comment]
Hi, hope [this helps](https://github.com/animorphcoop/journey-coop/commit/433e3c9aa2b6a5c7f781a26ec90c11ca9e79a8bf), feel welcome to reopen!
